#!/usr/bin/env python3
"""
Launcher main.py - starts the login which will launch main_app.py when successful.
This file was autogenerated to integrate the login flow.
"""
from login import show_login

if __name__ == "__main__":
    show_login()
